CREATE USER PLS_Utl IDENTIFIED BY yourpassword
/
GRANT CONNECT, RESOURCE TO PLS_Utl
/
GRANT CREATE ANY CONTEXT TO PLS_Utl
/
GRANT CREATE PUBLIC SYNONYM TO PLS_Utl
/
GRANT UNLIMITED TABLESPACE TO PLS_Utl
/
GRANT CREATE VIEW TO PLS_Utl
/
GRANT EXECUTE ON DBMS_RLS TO PLS_Utl
/
